require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AlbumOwnedsController do

  # This should return the minimal set of attributes required to create a valid
  # AlbumOwned. As you add validations to AlbumOwned, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "datewished" => "2014-12-03" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AlbumOwnedsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all album_owneds as @album_owneds" do
      album_owned = AlbumOwned.create! valid_attributes
      get :index, {}, valid_session
      assigns(:album_owneds).should eq([album_owned])
    end
  end

  describe "GET show" do
    it "assigns the requested album_owned as @album_owned" do
      album_owned = AlbumOwned.create! valid_attributes
      get :show, {:id => album_owned.to_param}, valid_session
      assigns(:album_owned).should eq(album_owned)
    end
  end

  describe "GET new" do
    it "assigns a new album_owned as @album_owned" do
      get :new, {}, valid_session
      assigns(:album_owned).should be_a_new(AlbumOwned)
    end
  end

  describe "GET edit" do
    it "assigns the requested album_owned as @album_owned" do
      album_owned = AlbumOwned.create! valid_attributes
      get :edit, {:id => album_owned.to_param}, valid_session
      assigns(:album_owned).should eq(album_owned)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new AlbumOwned" do
        expect {
          post :create, {:album_owned => valid_attributes}, valid_session
        }.to change(AlbumOwned, :count).by(1)
      end

      it "assigns a newly created album_owned as @album_owned" do
        post :create, {:album_owned => valid_attributes}, valid_session
        assigns(:album_owned).should be_a(AlbumOwned)
        assigns(:album_owned).should be_persisted
      end

      it "redirects to the created album_owned" do
        post :create, {:album_owned => valid_attributes}, valid_session
        response.should redirect_to(AlbumOwned.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved album_owned as @album_owned" do
        # Trigger the behavior that occurs when invalid params are submitted
        AlbumOwned.any_instance.stub(:save).and_return(false)
        post :create, {:album_owned => { "datewished" => "invalid value" }}, valid_session
        assigns(:album_owned).should be_a_new(AlbumOwned)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        AlbumOwned.any_instance.stub(:save).and_return(false)
        post :create, {:album_owned => { "datewished" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested album_owned" do
        album_owned = AlbumOwned.create! valid_attributes
        # Assuming there are no other album_owneds in the database, this
        # specifies that the AlbumOwned created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        AlbumOwned.any_instance.should_receive(:update_attributes).with({ "datewished" => "2014-12-03" })
        put :update, {:id => album_owned.to_param, :album_owned => { "datewished" => "2014-12-03" }}, valid_session
      end

      it "assigns the requested album_owned as @album_owned" do
        album_owned = AlbumOwned.create! valid_attributes
        put :update, {:id => album_owned.to_param, :album_owned => valid_attributes}, valid_session
        assigns(:album_owned).should eq(album_owned)
      end

      it "redirects to the album_owned" do
        album_owned = AlbumOwned.create! valid_attributes
        put :update, {:id => album_owned.to_param, :album_owned => valid_attributes}, valid_session
        response.should redirect_to(album_owned)
      end
    end

    describe "with invalid params" do
      it "assigns the album_owned as @album_owned" do
        album_owned = AlbumOwned.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AlbumOwned.any_instance.stub(:save).and_return(false)
        put :update, {:id => album_owned.to_param, :album_owned => { "datewished" => "invalid value" }}, valid_session
        assigns(:album_owned).should eq(album_owned)
      end

      it "re-renders the 'edit' template" do
        album_owned = AlbumOwned.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AlbumOwned.any_instance.stub(:save).and_return(false)
        put :update, {:id => album_owned.to_param, :album_owned => { "datewished" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested album_owned" do
      album_owned = AlbumOwned.create! valid_attributes
      expect {
        delete :destroy, {:id => album_owned.to_param}, valid_session
      }.to change(AlbumOwned, :count).by(-1)
    end

    it "redirects to the album_owneds list" do
      album_owned = AlbumOwned.create! valid_attributes
      delete :destroy, {:id => album_owned.to_param}, valid_session
      response.should redirect_to(album_owneds_url)
    end
  end

end
